# Generated by Django 4.1.7 on 2023-03-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingbuilder', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_anschrift', models.CharField(max_length=100)),
                ('customer_plz', models.CharField(default='00000', max_length=100)),
                ('customer_anzahl_teilnehmer', models.CharField(max_length=100)),
                ('customer_komentar', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(default='000', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('page_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landingbuilder.page')),
            ],
        ),
    ]
